### ISSUE TITLE
Уведомление на почту о ошибках при архивировании

### ISSUE THREAD

**Issue by djbelyak** [AlexanderPuzanov/1c-backup-cmd-ru#1]
Для отправки писем скриптом будут использоваться две сторонние программы со «свободным» лицензированием.
Blat (http://sourceforge.net/projects/blat/) — для отправки почты.
stunnel (https://www.stunnel.org/index.html) — для SSL шифрования (требование многих почтовых сервисов).

**Comment by AlexanderPuzanov** [comment]
«Для отправки писем скриптом будут использоваться две сторонние программы со «свободным» лицензированием.
Blat (http://sourceforge.net/projects/blat/) — для отправки почты.
stunnel (https://www.stunnel.org/index.html) — для SSL шифрования (требование многих почтовых сервисов).»
https://smartprogress.do/goal/86998/
